version: "2"

services:
  nginx:
    build: ./nginx
    env_file:
      - ./config.env
    volumes:
      - ./vhosts:/etc/nginx/vhosts
      - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

  sftpgo:
    image: drakkan/sftpgo:latest
    volumes:
      - sftpgo-data:/srv/sftpgo
      - sftpgo-config:/var/lib/sftpgo

volumes:
  sftpgo-data:
    external: true

  sftpgo-config:
    external: true