version: "3.9"

services:
  nginx:
    build: ./nginx
    env_file:
      - ./config.env
    volumes:
      - ./vhosts:/etc/nginx/vhosts
      - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - sftpgo
      - mattermost

  # Open Source File Transfer which also has event notifications
  sftpgo:
    image: drakkan/sftpgo:latest
    volumes:
      - sftpgo-data:/srv/sftpgo
      - sftpgo-config:/var/lib/sftpgo

  # Chat and Productivity (Open Source Slack)
  mattermost:
    container_name: mattermost
    image: mattermost/mattermost-enterprise-edition
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    volumes:
      - mattermost:/mattermost
    environment:
      - MM_SQLSETTINGS_DRIVERNAME
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@mattermost-db:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_BLEVESETTINGS_INDEXDIR
      - MM_SERVICESETTINGS_SITEURL=https://mattermost
    depends_on:
      - mattermost-db

  mattermost-db:
    container_name: mattermost-db
    image: postgres:alpine
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    volumes:
      - mattermost-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost

  gitea:
    image: gitea/gitea:1.17.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - gitea:/data
    ports:
      - "222:22"

volumes:
  sftpgo-data:
    external: true

  sftpgo-config:
    external: true

  mattermost:
    external: true

  mattermost-db:
    external: true

  gitea:
    external: true