version: "3.9"

services:
  nginx:
    build: ./nginx
    env_file:
      - ./config.env
    volumes:
      - ./vhosts:/etc/nginx/vhosts
      - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - sftpgo
      - mattermost

  # Open Source File Transfer which also has event notifications
  sftpgo:
    image: drakkan/sftpgo:latest
    volumes:
      - sftpgo-data:/srv/sftpgo
      - sftpgo-config:/var/lib/sftpgo

  # Chat and Productivity (Open Source Slack)
  mattermost:
    container_name: mattermost
    image: mattermost/mattermost-enterprise-edition
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    volumes:
      - mattermost:/mattermost
    environment:
      - MM_SQLSETTINGS_DRIVERNAME
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@mattermost-db:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_BLEVESETTINGS_INDEXDIR
      - MM_SERVICESETTINGS_SITEURL=https://mattermost
    depends_on:
      - mattermost-db

  mattermost-db:
    container_name: mattermost-db
    image: postgres:alpine
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    volumes:
      - mattermost-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost

  # Open Source Version Control
  gitea:
    image: gitea/gitea:1.17.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - gitea:/data
    ports:
      - "222:22"

  vaultwarden:
    container_name: vaultwarden
    image: "vaultwarden/server:latest"
    volumes:
      - vaultwarden-data:/data

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    environment:
      TZ: 'America/Atlanta'
      WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - pihole-etc:/etc/pihole
      - pihold-dnsmasq.d:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

  nextcloud:
    container_name: nextcloud-aio-mastercontainer
    image: nextcloud/all-in-one:latest-arm64
    restart: unless-stopped
    volumes:
      - nextcloud:/mnt/docker-aio-config
      - /var/run/docker.sock.raw:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
      - "3478:3478/TCP"
      - "3478:3478/UDP"
    environment:
      - DOCKER_SOCKET_PATH=/var/run/docker.sock.raw
      - APACHE_PORT=11000
      # - APACHE_IP_BINDING=127.0.0.1 # Should be set when running behind a reverse proxy that is running on the same host. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      # - TALK_PORT=3478 # This allows to adjust the port that the talk container is using.
      # - NEXTCLOUD_DATADIR=/mnt/ncdata # Allows to set the host directory for Nextcloud's datadir. See https://github.com/nextcloud/all-in-one#how-to-change-the-default-location-of-nextclouds-datadir
      # - NEXTCLOUD_MOUNT=/mnt/ # Allows the Nextcloud container to access the chosen directory on the host. See https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
      # - DOCKER_SOCKET_PATH=/var/run/docker.sock # Needs to be specified if the docker socket on the host is not located in the default '/var/run/docker.sock'. Otherwise mastercontainer updates will fail.
      # - DISABLE_BACKUP_SECTION=true # Setting this to true allows to hide the backup section in the AIO interface.
      # - NEXTCLOUD_UPLOAD_LIMIT=10G # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-upload-limit-for-nextcloud
      # - NEXTCLOUD_MAX_TIME=3600 # Can be adjusted if you need more. See https://github.com/nextcloud/all-in-one#how-to-adjust-the-max-execution-time-for-nextcloud
      # - TRUSTED_CACERTS_DIR=/path/to/my/cacerts # CA certificates in this directory will be trusted by the OS of the nexcloud container (Useful e.g. for LDAPS) See See https://github.com/nextcloud/all-in-one#how-to-trust-user-defiend-certification-authorities-ca
      # - COLLABORA_SECCOMP_DISABLED=false # Setting this to true allows to disable Collabora's Seccomp feature. See https://github.com/nextcloud/all-in-one#how-to-disable-collaboras-seccomp-feature


volumes:
  sftpgo-data:
    external: false

  sftpgo-config:
    external: false

  mattermost:
    external: false

  mattermost-db:
    external: false

  gitea:
    external: false

  vaultwarden-data:
    external: false

  pihole-etc:
    external: false

  pihold-dnsmasq.d:
    external: false


  nextcloud:
    external: false
    name: nextcloud_aio_mastercontainer
